
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: globalfit-test-argo-
spec:
  entrypoint: globalfit-argo
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
  - metadata:
      name: workdir                     # name of volume claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi                  # Gi => 1024 * 1024 * 1024

  templates:
  - name: globalfit-argo
    steps:
    - - name: build
        template: run
        
  - name: run
    container:
      image: nooraangelva/global_fit:1.0
      command: [sh, -c]
      args: ["git clone https://github.com/nooraangelva/Global-fit-package.git tmp; cd tmp/chic_pol_global_fit; make all; scripts/run_nrqcd_fit.sh; cd SDCs_Carlos_interpol/fit_1S0_only_LP+NLO/fit_results_report.pdf; "]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
    

