# This is a basic workflow that is manually triggered

name: Testing a pull_request

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  Test:
    runs-on: nooraangelva/global_fit
    name: Set up 
    steps:
    - uses: actions/checkout@v2
    - name: Build the platform
      run: |
        echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       
