name: Test workflow on minikube + argo 
on:
  pull_request:
    branches:
    - master
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    name: AOD2NanoAOD test - minikube + argo
    steps:
    - uses: actions/checkout@v2
    - name: Start a minikube cluster
      run: |
        minikube start
        n=0; until ((n >= 60)); do kubectl -n default get serviceaccount default -o name && break; n=$((n + 1)); sleep 1; done; ((n < 60))
    - name: Set up persistent volume and storage pod
      run: |
        kubectl apply -f volumes.yaml   
    - name: Set up argo
      run: |
        kubectl create ns argo
        kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-postgres.yaml
        curl -sLO https://github.com/argoproj/argo/releases/download/v3.0.0-rc6/argo-linux-amd64.gz
        gunzip argo-linux-amd64.gz
        chmod +x argo-linux-amd64 
        sudo mv ./argo-linux-amd64 /usr/local/bin/argo
        argo version
    - name: Submit the argo test workflow
      run: |
        argo submit -n argo  --wait argo-workflow.yaml
        argo get -n argo @latest
